name: GitHub Pages Deploy

on:
    # Allows running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            # Compile the SCSS files into CSS
            - name: Compile CSS
              run: |
                echo Beginning CSS compilation!

            # Clean up repository
            - name: Clean repo
              run: |
                echo Cleaning repository!
